### PR TITLE
Update Bot.py

### LINKED ISSUE #32: New Endscreen for victories bricks the bot.
The beginning loop now does not exit out of the victory screen for AI battles, since the bot is using preset x,y values it should be an easy fix to add an extra couple of values for the bot to click on when the match ends.

### PR DESCRIPTION
**Pull request by E7t7t7**
change req new button

### CODE REVIEW

**Review by MOj0 — APPROVED** [review]
I hope you ran and tested it, since I haven't :smile:

**Comment by E7t7t7** [comment]
> I hope you ran and tested it, since I haven't 😄

brother i just added the coordinates i tested nothing was at work ill try it now. for note you had me add the X Y on line 261 i will test now

**Comment by E7t7t7** [comment]
> I hope you ran and tested it, since I haven't 😄

running that particular edit locks up in same location any other ideas?

**Comment by MOj0** [comment]
Done here https://github.com/MOj0/LoR-Bot/pull/41

**Pull request closed without merging**
